from __future__ import annotations
import re
from typing import Optional


class UnifiedDiff:
    """Minimal unified-diff validator/parser.

    This is intentionally small: it ensures the text looks like a unified diff
    (contains at least one 'diff --git' and file markers) and returns a
    simple structured result. For stronger validation, expand this to a full
    parser or use existing libraries.
    """

    DIFF_GIT_RE = re.compile(r"^diff --git a/.+ b/.+", re.MULTILINE)
    PATH_RE = re.compile(r"^(?:---|\+\+\+) [ab]/(?P<path>.+)$", re.MULTILINE)

    @classmethod
    def looks_like_diff(cls, text: str) -> bool:
        text = cls._strip_fences(text)
        if not text or not text.strip():
            return False
        if cls.DIFF_GIT_RE.search(text):
            return True
        # fallback: check for both --- a/ and +++ b/ markers
        return bool(re.search(r"--- a/.+\n\+\+\+ b/.+", text))

    @classmethod
    def parse(cls, text: str) -> Optional[dict]:
        """Return a small structure for the diff or None if invalid."""
        cleaned = cls._strip_fences(text)
        if not cls.looks_like_diff(cleaned):
            return None
        paths = []
        for m in cls.PATH_RE.finditer(cleaned):
            paths.append(m.group("path"))
        return {"paths": list(dict.fromkeys(paths)), "raw": cleaned}

    @staticmethod
    def _strip_fences(text: str) -> str:
        """Remove common Markdown/code fences like ```diff ... ``` around the diff."""
        if not text:
            return text
        # If text contains triple-backtick fences, extract middle content
        if "```" in text:
            parts = text.split("```")
            # If there's content between fences, return it (handles ```diff)
            if len(parts) >= 3:
                cleaned = parts[1].strip()
                # Remove a stray leading "diff" line generated by codefence labels
                lines = cleaned.splitlines()
                if len(lines) >= 2 and lines[0].strip() == "diff" and lines[1].startswith("diff --git"):
                    return "\n".join(lines[1:]).strip()
                return cleaned
        return text


__all__ = ["UnifiedDiff"]
